### GET TOOELE TECH ROUTE
GET http://localhost:3000/ttech HTTP/1.1

### GET THE ROOT PATH
GET http://localhost:3000/ HTTP/1.1

### GET ALL STUDENTS ROUTE
GET http://localhost:3000/students HTTP/1.1

### GET ONE STUDENT
GET http://localhost:3000/students/65bbf67a828631d0789b85d5 HTTP/1.1

### POST ONE STUDENT (CREATE) 
POST http://localhost:3000/students HTTP/1.1
content-type: application/json

{
  "firstName": "Paul",
  "lastName": "Walker",
  "email": "pwalker@test.com",
  "age": 29,
  "currentCollege": "BYU-Idaho"
}

### PUT/PATCH UPDATE STUDENTS 
PUT http://localhost:3000/students/65bbf67a828631d0789b85d5 HTTP/1.1
content-type: application/json

{
  "firstName": "Preston",
  "lastName": "Walker",
  "email": "pres_walker@test.com",
  "age": 29,
  "currentCollege": "BYU-Hawaii"
}

###  DELETE STUDENTS ROUTE
DELETE http://localhost:3000/students/65bbf67a828631d0789b85d5 HTTP/1.1

